FROM python:3.8-slim-buster
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

# Install using traditional requirements.txt
RUN pip install -r requirements.txt

# Copy flask web-app
COPY ./web_app.py /app

# Run flask web-app
ENTRYPOINT [ "python" ]
CMD [ "web_app.py" ]